name: Generate Modpack

on:
  workflow_dispatch:  # Allow manual triggering of the workflow
  push:
    branches:
      - main  # Replace with the branch you want to trigger the release

jobs:
  generate_modpack:
    runs-on: ubuntu-latest

    steps:
    - name: Request user input for release version and name
      id: input
      run: |
        echo "Enter the release version:"
        read RELEASE_VERSION
        echo "Enter the release name:"
        read RELEASE_NAME
        echo "::set-output name=release_version::$RELEASE_VERSION"
        echo "::set-output name=release_name::$RELEASE_NAME"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '8'  # Specify Java 8
        distribution: 'zulu'  # Specify Zulu distribution for Java 8
    - name: Copy files to modpack directory
      run: |
        mkdir modpack
        cp -r mods config scripts modpack/
        echo "overrides" > modpack/overrides

    - name: Create manifest.json
      run: |
        echo '{
          "minecraft": {
            "version": "1.12.2",
            "modLoaders": [
              {
                "id": "forge-14.23.5.2859",
                "primary": true
              }
            ]
          },
          "manifestType": "minecraftModpack",
          "manifestVersion": 1,
          "name": "Mechanical Sorcery",  # Replace with the desired release name
          "version": "1.0.1",  # Replace with the desired release version
          "author": "Compec Someoneidk 0mori Nibiru",
          "files": [],
          "overrides": "overrides"
        }' > modpack/manifest.json

    - name: Package modpack
      run: |
        zip -r "Mechanical_Sorcery_1.0.1.zip" modpack

    - name: Upload modpack artifact
      uses: actions/upload-artifact@v2
      with:
        name: Mechanical_Sorcery_1.0.1
        path: Mechanical_Sorcery_1.0.1.zip
