name: Generate Modpack

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version for the modpack'
        required: true
      release_name:
        description: 'Release name for the modpack'
        required: true

jobs:
  generate_modpack:
    runs-on: ubuntu-latest

    steps:
    - name: Set up input parameters
      id: input
      run: |
        echo "::set-output name=release_version::$INPUT_RELEASE_VERSION"
        echo "::set-output name=release_name::$INPUT_RELEASE_NAME"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to modpack directory
      run: |
        mkdir modpack
        cp -r mods config scripts modpack/
        echo "overrides" > modpack/overrides

    - name: Create manifest.json
      run: |
        # Read the template manifest.json
        cat > modpack/manifest.json << EOF
        {
          "minecraft": {
            "version": "1.12.2",
            "modLoaders": [
              {
                "id": "forge-14.23.5.2859",
                "primary": true
              }
            ]
          },
          "manifestType": "minecraftModpack",
          "manifestVersion": 1,
          "name": "${{ steps.input.outputs.release_name }}",
          "version": "${{ steps.input.outputs.release_version }}",
          "author": "Compec Someoneidk 0mori Nibiru",
          "files": [],
          "overrides": "overrides"
        }
        EOF

    - name: Package modpack
      run: |
        zip -r "${{ steps.input.outputs.release_name }}_${{ steps.input.outputs.release_version }}.zip" modpack

    - name: Upload modpack artifact
      uses: actions/upload-artifact@v2
      with:
        name: "${{ steps.input.outputs.release_name }}_${{ steps.input.outputs.release_version }}"
        path: "${{ steps.input.outputs.release_name }}_${{ steps.input.outputs.release_version }}.zip"
      with:
        name: Mechanical_Sorcery_1.0.1
        path: Mechanical_Sorcery_1.0.1.zip
