name: Generate Modpack

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version for the modpack'
        required: true
      release_name:
        description: 'Release name for the modpack'
        required: true

jobs:
  generate_modpack:
    runs-on: ubuntu-latest

    steps:
    - name: Set up input parameters
      id: input
      run: |
        echo "::set-output name=release_version::$INPUT_RELEASE_VERSION"
        echo "::set-output name=release_name::$INPUT_RELEASE_NAME"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to modpack directory
      run: |
        mkdir modpack
        cp -r mods config scripts modpack/
        echo "overrides" > modpack/overrides

    - name: Create manifest.json
      run: |
        # Read the template manifest.json and replace the variables
        RELEASE_VERSION="${{ steps.input.outputs.release_version }}"
        RELEASE_NAME="${{ steps.input.outputs.release_name }}"
        cat << EOF > modpack/manifest.json
        {
          "minecraft": {
            "version": "1.12.2",
            "modLoaders": [
              {
                "id": "forge-14.23.5.2859",
                "primary": true
              }
            ]
          },
          "manifestType": "minecraftModpack",
          "manifestVersion": 1,
          "name": "$RELEASE_NAME",
          "version": "$RELEASE_VERSION",
          "author": "Compec Someoneidk 0mori Nibiru",
          "files": [],
          "overrides": "overrides"
        }
        EOF

    - name: Package modpack
      run: |
        # Replace spaces with underscores in the zip file name
        ZIP_FILE_NAME="${{ steps.input.outputs.release_name }}_${{ steps.input.outputs.release_version }}.zip"
        zip -r "$ZIP_FILE_NAME" modpack

    - name: Upload modpack artifact
      uses: actions/upload-artifact@v2
      with:
        name: "$ZIP_FILE_NAME"
        path: "$ZIP_FILE_NAME"
