name: Generate Modpack

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the release

jobs:
  generate_modpack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 1.12

    - name: Copy files to modpack directory
      run: |
        mkdir modpack
        cp -r mods config scripts modpack/
        echo "overrides" > modpack/overrides

    - name: Create manifest.json
      run: |
        echo '{
          "minecraft": {
            "version": "1.12.2",
            "modLoaders": [
              {
                "id": "forge-14.23.5.2859",
                "primary": true
              }
            ]
          },
          "manifestType": "minecraftModpack",
          "manifestVersion": 1,
          "name": "Mechanical Sorcery",  # Replace with the desired release name
          "version": "1.0.1",  # Replace with the desired release version
          "author": "Compec Someoneidk 0mori Nibiru",
          "files": [],
          "overrides": "overrides"
        }' > modpack/manifest.json

    - name: Package modpack
      run: |
        zip -r "Mechanical_Sorcery_1.0.1.zip" modpack

    - name: Upload modpack artifact
      uses: actions/upload-artifact@v2
      with:
        name: Mechanical_Sorcery_1.0.1
        path: Mechanical_Sorcery_1.0.1.zip
